### ISSUE TITLE
Support for other databases?

### ISSUE THREAD

**Issue by joshua-mng** [kwaazaar/Resonance#29]
Do you have any plan to create support for oracle database? (also postgresql too).

Thank you

**Comment by kwaazaar** [comment]
Sorry, but I'm no longer updating this library. I myself ended up using only the MsSql database, because under load, MsSql by far outperforms MySql. 

Also, using this library only makes sense if for whatever reason you cannot use dedicated messaging infrastructure, like RabbitMQ, Kafka etc.
